version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
  - dependency-name: ember-cli
    versions:
    - 3.24.0
  - dependency-name: eslint
    versions:
    - 7.17.0
    - 7.19.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.1
