name: Lint

env:
  FORCE_COLOR: 1

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.5.1
          node-version: 16.x
          args: "--frozen-lockfile"
      - name: Run Lint
        run: pnpm lint

  typescript-compatibility:
    name: Type checking - ${{ matrix.typescript-scenario }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typescript-scenario:
          - typescript@5.0
          - typescript@5.1
          - typescript@next

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 16.x
          args: "--frozen-lockfile"
      - name: Update TS version
        run: pnpm add -D ${{ matrix.typescript-scenario }}
        working-directory: ember-phone-input
      - name: Type checking
        run: pnpm lint:types
        working-directory: ember-phone-input
